FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ./src ./src

# Expose the default Cloud Run port
EXPOSE 8080

# Start the server using the PORT environment variable
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]
